# Generated by Django 3.0.4 on 2020-06-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('branch', models.CharField(max_length=225)),
                ('directorate', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('program_service', models.CharField(max_length=225)),
                ('pub_date', models.DateTimeField()),
                ('giturl', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
